### ISSUE TITLE
Pictures in the article found 404 error

### ISSUE THREAD

**Issue by asd7227600** [kodecocodes/kotlin-style-guide#2]
As the title described, some pictures is unreachable. Wish it can be fixed. Thanks.

**Comment by designatednerd** [comment]
@asd7227600 Yes, that's correct - those are noted as being updated soon, since we have not finished getting that completely together for Kotlin yet. The pictures which were there were only relevant for Java, unfortunately, which is why we removed them for the work in progress. 

Will leave this open as a reminder to get this up and running. Thanks!
